---
framework: mocha
postMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*-spec.js"
preMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*-spec.js"
preRun:
     command:
        - npm install 
        - npm i react
        - npm run build
postRun:
     command:
        - node --version
version: 1.0
configFile: ./test/mocha.opts
